# -*- coding: utf-8 -*-
"""Cifar10Dataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10D8az3ZXbnf6_FeitvXBtIkw_1duW-sn
"""

import tensorflow as tf
from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt
import numpy as np

(X_train, y_train), (X_test, y_test) = datasets.cifar10.load_data()
X_train.shape

#Training samples are 50k, 32*32 image, 3 is for rgb channel
X_test.shape

y_train = y_train.flatten() #reshaping
y_train[:5]

classes = ["airplane","automobile","bird","cat","deer", "dog","frog", "horse", "ship", "truck"]

classes[9]

def plot_sample(X, y, index):
  plt.figure(figsize=(15,2))
  plt.imshow(X[index])
  plt.xlabel(classes[y[index]])

plot_sample(X_train, y_train, 0)

plot_sample(X_train, y_train, 3)

X_train = X_train/255
X_test = X_test/255

#build ANN
# ann = models.Sequential([
#     layers.Flatten(input_shape=(32,32,3)),
#     layers.Dense(3000, activation='relu'),
#     layers.Dense(1000, activation='relu'),
#     layers.Dense(10, activation='softmax')
# ])

# ann.compile(optimizer='SGD',
#              loss='sparse_categorical_crossentropy',
#              metrics=['accuracy'])

# ann.fit(X_train, y_train, epochs=5) #repeat the process 5 times, training



cnn = models.Sequential([
    #cnn layers
    layers.Conv2D(filters=32, activation='relu', kernel_size=(3,3), input_shape=(32,32,3)),
    layers.MaxPooling2D((2,2)),

    layers.Conv2D(filters=64, activation='relu', kernel_size=(3,3)),
    layers.MaxPooling2D((2,2)),

    #dense network
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')




    #softmax will normalize your probablity
    #sigmoid 0.45, 0.67 , softmax = 0.45/(0.45+0.67)
])

cnn.compile(optimizer='adam',
               loss='sparse_categorical_crossentropy',
               metrics=['accuracy'])

cnn.fit(X_train, y_train, epochs=10)

y_test = y_test.reshape(-1,)

cnn.evaluate(X_test, y_test)



plot_sample(X_test, y_test, 3)

y_pred = cnn.predict(X_test)
y_pred[:5]

y_classes = np.argmax(y_pred, axis=1)
y_classes[:5]

y_test[:5]

index = 7
plot_sample(X_test, y_test, index)

def predict_test_image(model, X_test, y_test, classes, index):
    img = X_test[index]                      # shape (32,32,3)
    img_input = np.expand_dims(img, axis=0)  # shape (1,32,32,3)

    pred_probs = model.predict(img_input)
    pred_class = np.argmax(pred_probs, axis=1)[0]

    actual_class = y_test[index]

    plt.imshow(img)
    plt.axis("off")
    plt.title(f"Predicted: {classes[pred_class]} | Actual: {classes[actual_class]}")
    plt.show()

    if pred_class == actual_class:
        print("✅ Correct Prediction")
    else:
        print("❌ Wrong Prediction")

# Example usage:
predict_test_image(cnn, X_test, y_test, classes, index=10)

#load image, resize to 32*32, normalize then predict

def predict_custom_image(model, image_path, classes):
    # Load image from file
    img = tf.keras.utils.load_img(image_path, target_size=(32, 32))
    img_array = tf.keras.utils.img_to_array(img)  # (32,32,3)

    # Normalize (same as training)
    img_array = img_array / 255.0

    # Add batch dimension: (1,32,32,3)
    img_input = np.expand_dims(img_array, axis=0)

    # Predict
    pred_probs = model.predict(img_input)
    pred_class = np.argmax(pred_probs, axis=1)[0]

    # Show image + prediction
    plt.imshow(img)
    plt.axis("off")
    plt.title(f"Predicted: {classes[pred_class]}")
    plt.show()

    print("Predicted class:", classes[pred_class])

# Example usage:
predict_custom_image(cnn, "Longbow.jpg", classes)

cnn.save("cifar10_cnn.h5")

import os
os.listdir()









